Repository onaio/gisida, pull requests merged in 2020-01, with the labels that each got.

#365 Add Security and Passwords to New Project Checklist
  docs/new-project-checklist.md
Labels: documentation

#355 Add tests for slice reducers for reducer createMapReducer
  src/store/reducers/createMapReducer/createMapReducer.js
  src/store/reducers/createMapReducer/openCategoriesReducer.js
  src/store/reducers/createMapReducer/openGroupsReducer.js
  src/store/reducers/createMapReducer/openMenuLevelsReducer.js
  src/store/reducers/createMapReducer/tests/activeLayerIdReducer.test.js
  src/store/reducers/createMapReducer/tests/activeLayerIdsReducer.test.js
  src/store/reducers/createMapReducer/tests/common.js
  src/store/reducers/createMapReducer/tests/currentRegionReducer.test.js
  src/store/reducers/createMapReducer/tests/currentStyleReducer.test.js
  src/store/reducers/createMapReducer/tests/defaultLayersReducer.test.js
  src/store/reducers/createMapReducer/tests/detailViewReducer.test.js
  src/store/reducers/createMapReducer/tests/filterReducer.test.js
  src/store/reducers/createMapReducer/tests/lastLayerSelectedReducer.test.js
  src/store/reducers/createMapReducer/tests/layerVisibilityReducer.test.js
  src/store/reducers/createMapReducer/tests/layersReducer.test.js
  src/store/reducers/createMapReducer/tests/mapLoadedReducer.test.js
  src/store/reducers/createMapReducer/tests/mapRenderedReducer.test.js
  src/store/reducers/createMapReducer/tests/menuIsOpenReducer.test.js
  src/store/reducers/createMapReducer/tests/menuScrollReducer.test.js
  src/store/reducers/createMapReducer/tests/oldLayerObjsReducer.test.js
  src/store/reducers/createMapReducer/tests/openCategories.test.js
  src/store/reducers/createMapReducer/tests/openMenuLevelsReducer.test.js
  src/store/reducers/createMapReducer/tests/primaryLayerReducer.test.js
  src/store/reducers/createMapReducer/tests/primarySubLayerReducer.test.js
  src/store/reducers/createMapReducer/tests/reloadLayerIdReducer.test.js
  src/store/reducers/createMapReducer/tests/reloadLayersReducer.test.js
  src/store/reducers/createMapReducer/tests/showFilterPanelReducer.test.js
  src/store/reducers/createMapReducer/tests/showSpinnerReducer.test.js
  src/store/reducers/createMapReducer/tests/timeSeriesReducer.test.js
  test/store/actions/actions.test.js
Labels: tests

#389 Handle iframe(superset) permissions
  build/gisida.js
  build/gisida.js.map
  src/utils/supAuth.js
Labels: extensibility

#354 [DNM] Type declarations
  .gitignore
  package.json
  src/store/actions/actions.js
  src/types/actionTypesInterface.ts
  src/types/actionsInterface.ts
  src/types/index.d.ts
  yarn.lock
Labels: Standardization, Wip

#326 Add docs for supported data sources
  README.md
Labels: documentation

#384 Reducers minor fixes
  build/gisida.js
  build/gisida.js.map
  package.json
  src/index.js
  src/store/initStore.js
  yarn.lock
Labels: bug

#330 Geojson Validation
  build/gisida.js
  build/gisida.js.map
  package.json
  src/index.js
  src/map/prepareLayer.js
  webpack.config.js
  yarn.lock
Labels: Standardization, gisida-core

#394 Render 0s as transparent fills/circle
  docs/labels.md
  package.json
  src/map/prepareLayer.js
  src/utils/commaFormatting.js
  test/store/reducers/reducers.test.js
Labels: extensibility, gisida-client, gisida-core
