Repository onaio/gisida, pull requests merged in 2020-02, with the labels that each got.

#395 Feature/392 contributing
  docs/CONTRIBUTING.md
Labels: gisida-core

#416 v1.3.3 Release
  build/gisida.js
  docs/CONTRIBUTING.md
  docs/labels.md
  package.json
  src/index.js
  src/map/addLayer.js
  src/map/prepareLayer.js
  src/store/initStore.js
  src/utils/commaFormatting.js
  test/store/reducers/reducers.test.js
  webpack.config.js
  yarn.lock
Labels: release

#417 Extra checks
  build/gisida.js
  build/gisida.js.map
  src/map/prepareLayer.js
Labels: bug

#421 Solve bug createMapReducer undefined when importing from gisida
  build/gisida.js
  build/gisida.js.map
  src/index.js
  src/store/reducers/createMapReducer/index.js
  src/store/reducers/index.js
  src/store/reducers/map/activeLayerIdReducer.js
  src/store/reducers/map/activeLayerIdsReducer.js
  src/store/reducers/map/createMapReducer.js
  src/store/reducers/map/currentRegionReducer.js
  src/store/reducers/map/currentStyleReducer.js
  src/store/reducers/map/defaultLayersReducer.js
  src/store/reducers/map/detailViewReducer.js
  src/store/reducers/map/filterReducer.js
  src/store/reducers/map/index.js
  src/store/reducers/map/lastLayerSelectedReducer.js
  src/store/reducers/map/layerVisibilityReducer.js
  src/store/reducers/map/layersReducer.js
  src/store/reducers/map/mapLoadedReducer.js
  src/store/reducers/map/mapRenderedReducer.js
  src/store/reducers/map/menuIsOpenReducer.js
  src/store/reducers/map/menuScrollReducer.js
  src/store/reducers/map/oldLayerObjsReducer.js
  src/store/reducers/map/openMenuLevelsReducer.js
  src/store/reducers/map/primaryLayerReducer.js
  src/store/reducers/map/primarySubLayerReducer.js
  src/store/reducers/map/reloadLayerIdReducer.js
  src/store/reducers/map/reloadLayersReducer.js
  src/store/reducers/map/showFilterPanelReducer.js
  src/store/reducers/map/showSpinnerReducer.js
  src/store/reducers/map/tests/activeLayerIdReducer.test.js
  src/store/reducers/map/tests/activeLayerIdsReducer.test.js
  src/store/reducers/map/tests/common.js
  src/store/reducers/map/tests/currentRegionReducer.test.js
  src/store/reducers/map/tests/currentStyleReducer.test.js
  src/store/reducers/map/tests/defaultLayersReducer.test.js
  src/store/reducers/map/tests/detailViewReducer.test.js
  src/store/reducers/map/tests/filterReducer.test.js
  src/store/reducers/map/tests/lastLayerSelectedReducer.test.js
  src/store/reducers/map/tests/layerVisibilityReducer.test.js
  src/store/reducers/map/tests/layersReducer.test.js
  src/store/reducers/map/tests/mapLoadedReducer.test.js
  src/store/reducers/map/tests/mapRenderedReducer.test.js
  src/store/reducers/map/tests/menuIsOpenReducer.test.js
  src/store/reducers/map/tests/menuScrollReducer.test.js
  src/store/reducers/map/tests/oldLayerObjsReducer.test.js
  src/store/reducers/map/tests/openMenuLevelsReducer.test.js
  src/store/reducers/map/tests/primaryLayerReducer.test.js
  src/store/reducers/map/tests/primarySubLayerReducer.test.js
  src/store/reducers/map/tests/reloadLayerIdReducer.test.js
  src/store/reducers/map/tests/reloadLayersReducer.test.js
  src/store/reducers/map/tests/showFilterPanelReducer.test.js
  src/store/reducers/map/tests/showSpinnerReducer.test.js
  src/store/reducers/map/tests/timeSeriesReducer.test.js
  src/store/reducers/map/timeSeriesReducer.js
Labels: bug, gisida-core
